spring:
  security:
    oauth2:
      client:
        registration:
          crypto-portfolio:
            client-id: crypto-portfolio
            client-secret: 28040d12-081f-48e0-8ba8-801003666428
            client-name: Crypto Portfolio
            scope: openid,offline_access
            redirect-uri: http://localhost:8080/login/oauth2/code/crypto-portfolio
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            provider: keycloak-provider  
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8081/auth/realms/CryptoInc
logging:
  level:
    root: INFO
    com.memorynotfound: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO